[target.aarch64-unknown-linux-musl]
linker = "clang"
rustflags = [
  # Use the mold linker
  "-C",
  "link-arg=-fuse-ld=mold",
  # Statically link the C runtime
  "-C",
  "target-feature=+crt-static",
  # Use only libraries/objects shipped with Rust
  "-C",
  "link-self-contained=yes",
]

[target.x86_64-unknown-linux-musl]
linker = "clang"
rustflags = [
  "-C",
  "link-arg=-fuse-ld=mold",
  "-C",
  "target-feature=+crt-static",
  "-C",
  "link-self-contained=yes",
]
