name: run_tests

on:
  workflow_call:

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTC_WRAPPER: "sccache"
  SCCACHE_GHA_ENABLED: "true"
  AWS_LC_SYS_PREBUILT_NASM: 1

jobs:
  tests:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-apple-darwin
          - x86_64-pc-windows-msvc

        include:
          - target: x86_64-unknown-linux-musl
            runner: ubuntu-24.04

          - target: aarch64-apple-darwin
            runner: macos-26

          - target: x86_64-pc-windows-msvc
            runner: windows-2025

    runs-on: ${{ matrix.runner }}
    steps:
    - name: Fetch repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
      with:
        target: ${{ matrix.target }}

    - name: Install system packages (musl)
      if: contains(matrix.target, '-musl')
      run: sudo apt-get install -y --no-install-recommends clang mold musl-tools

    - name: Install system packages (gnu)
      if: contains(matrix.target, '-gnu')
      run: sudo apt-get install -y --no-install-recommends clang mold

    - name: Fetch cache
      uses: mozilla-actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696 # v0.0.10

    - name: Set up mise
      uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
      with:
        version: "2025.10.4"

    - name: Build tests
      run: cargo test --no-run --target ${{ matrix.target }}

    - name: Run tests
      run: cargo test --target ${{ matrix.target }}
